/* Local regression checks for request deduplication and stale-result handling. */
const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const html = fs.readFileSync('ControlPanel.html', 'utf8');
const source = html.slice(html.indexOf('  var PROFILE_CACHE='), html.indexOf('  function updateMemberAvatars'));
let now = 1000;
const calls = [], results = [], errors = [];
const context = { Date: { now: () => now }, api: (ok, fail, name, id) => calls.push({ ok, fail, name, id }), onError: e => errors.push(e) };
vm.createContext(context);
vm.runInContext(source, context);
const request = id => context.requestProfile(id, data => results.push(data));
request('123'); request('123');
assert.equal(calls.length, 1, 'overlapping profile loads share one RPC');
calls[0].ok({ history: [1] });
assert.equal(results.length, 2, 'both listeners receive the result');
request('123');
assert.equal(calls.length, 1, 'recent profile is reused');
now += 30001;
request('123');
assert.equal(calls.length, 2, 'expired profile refreshes');
context.PROFILE_GEN++; context.PROFILE_CACHE = {};
request('123');
assert.equal(calls.length, 3, 'roster refresh starts a fresh request');
calls[1].ok({ stale: true });
assert.equal(results.length, 3, 'old-generation response is ignored');
calls[2].fail(new Error('temporary failure'));
request('123');
assert.equal(calls.length, 4, 'failed requests can retry');
calls[3].ok({ fresh: true });
assert.equal(results.length, 4);
assert.equal(errors.length, 1);
console.log('Profile deduplication, expiry, invalidation, stale responses and retry: passed');
